server:
  port: 8080
  servlet:
    context-path: /mcpservice

spring:
  ai:
    mcp:
      server:
        name: mcp-java-service
        version: 0.0.1
        protocol: STREAMABLE
    openai:
      api-key: ${OPENAI_API_KEY:}
  datasource:
    url: jdbc:postgresql://localhost/companydb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${POSTGRES_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
  sql:
    init:
      mode: always
springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  cors:
    allowed-origins: http://localhost:5174
